### ISSUE TITLE
where is "slow_agent" directory?

### ISSUE THREAD

**Issue by lxqpku** [SwiftSage/SwiftSage#3]
Traceback (most recent call last):
  File "eval_agent_fast_slow.py", line 13, in <module>
    from eval_utils import load_model, findValidActionNew, load_variation, get_model_output, findValidActionWithSystem2, getFilteredValidActions, sbert_search, clean_look, is_action_failed
  File "/home/liuxiaoqian/SwiftSage-main/eval_utils.py", line 12, in <module>
    from slow_agent.utils import completion_with_backoff, generate_followup_prompt, load_triplets, sample_few_shot
ModuleNotFoundError: No module named 'slow_agent'

**Comment by yuchenlin** [comment]
just fixed this
