### ISSUE TITLE
AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'

### ISSUE THREAD

**Issue by prateekchhikara** [SwiftSage/SwiftSage#4]
I am getting the following error while running ds_train.sh. Any resolution for this?

`AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'`

**Comment by yuchenlin** [comment]
Hi @prateekchhikara , this may be related to your coda toolkit version. I found a similar issue in the official deepspeed repo, hope it could help: https://github.com/microsoft/DeepSpeed/issues/1846

**Comment by prateekchhikara** [comment]
Yeah, @yuchenlin I updated my cuda-toolkit version and not it is working perfectly.
