### ISSUE TITLE
The result of ReAct in paper cannot be reproduced

### ISSUE THREAD

**Issue by siyuyuan** [SwiftSage/SwiftSage#8]
Thanks for your great work! I have used your code to reproduce the react's results. However, I found that my results are much lower than the results of your paper. For example, for tasks 8-2, the score in your paper is 8.0. However, I ran three times, and the score is still only 1.3333. This is the running code.
```
for task in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
do
    python eval_agent_react.py \
        --task_nums $task \
        --set test_mini \
        --no_stop \
        --env_step_limit 100 \
        --simplification_str easy \
        --prompt_file baselines/ReAct_baseline/prompt.jsonl \
        --output_path ReAct_logs/gpt-4-1106-preview \
        --model_name gpt-4-1106-preview
done
```

Do you know why it happened?

**Comment by yuchenlin** [comment]
Hi Siyu, sorry for the delay. I think this may be about the non-determinism of gpt-4 api which even if we set temp=0 can still produce some variance in the outputs and then cause the difference over time.
